on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    name: Create release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-iat
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4
        id: release
        with:
          token: ${{ steps.create-iat.outputs.token }}

  upload:
    name: Upload executables
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      # setup ruby environment before running jonabc/setup-licensed
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build:artifacts
      - name: Upload executables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r '.version' ./package.json)
          gh release upload ${{ needs.release.outputs.tag_name }} \
            ${GITHUB_WORKSPACE}/artifacts/plugin.zip \
