on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    name: Create release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-iat
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4
        id: release
        with:
          token: ${{ steps.create-iat.outputs.token }}
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/${{ steps.release.outputs.tag_name }}.zip

