on:
  push:
    branches:
      - "release-please-**"

permissions:
  contents: write
  pull-requests: write

name: Update Manifest

jobs:
  update_manifest:
    name: Update manifest.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Update Manifest Version
        run: |
          echo "=========Pushing changes to=========="
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          pnpm syncVersion
          git add plugin/manifest.json
          git commit -m "chore: update manifest version"
          git push origin HEAD
