on:
  push:
    branches:
      - "release-please-**"

permissions:
  contents: write
  pull-requests: write

name: Update Manifest

jobs:
  release:
    name: Create release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-iat
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4
        id: release
        with:
          token: ${{ steps.create-iat.outputs.token }}

  update_manifest:
    name: Update manifest.json
    runs-on: ubuntu-latest
    steps:
      # setup ruby environment before running jonabc/setup-licensed
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - uses: actions/checkout@v4
      - run: |
          git fetch
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "git checkout ${{fromJson(needs.release.outputs.pr).headBranchName}}"
          git checkout ${{fromJson(needs.release.outputs.pr).headBranchName}}

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Update Manifest Version
        run: |
          echo "=========Pushing changes to=========="
          echo "${{fromJson(needs.release.outputs.pr).headBranchName}}"
          echo "@@@@@@@"
          pnpm syncVersion
          git add plugin/manifest.json
          git commit -m "chore: update manifest version"
          git push origin HEAD
